name: Build Xamarin.Android app

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: |
        cd
        nuget restore SuperSetTimer.sln

    - name: Build
      run: msbuild SuperSetTimer\SuperSetTimer /t:PackageForAndroid /p:Configuration=Debug
