name: Build Xamarin.Android app

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build      
      run: |
        cd SuperSetTimer\SuperSetTimer
        dotnet build --configuration Release --no-restore
        msbuild SuperSetTimer.csproj /t:PackageForAndroid /p:Configuration=Debug
