name: Build Xamarin.Android app

on: [push]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      APPLICATION_NAME: SuperSetTimer
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Solution
        run: msbuild ./${{ env.APPLICATION_NAME }}.sln /restore /p:Configuration=Debug

      - name: Create and Sign the APK
        run: msbuild ./${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.Android\${{ env.APPLICATION_NAME }}.Android.csproj /t:SignAndroidPackage /p:Configuration=Debug /p:OutputPath=bin\Debug\

      - name: List folder content
        run: dir ${{ env.APPLICATION_NAME }}.Android\bin\Debug

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApplication.apk
          path: ${{ env.APPLICATION_NAME }}.Android\bin\Debug\com.companyname.supersettimer-Signed.apk
